ChatController Testing
Bojo992/CS4337-Project pull request #16
Opened 2024-11-20 16:19 UTC by plutowootoe

2024-11-21 17:57 UTC, Bojo992 requested changes
Can you change which brunch you are pushing to dev, I will take a look at the tests later today, sorry just seen pr.

2024-11-21 18:01 UTC, oakwoodwolf approved these changes
lgtm

2024-11-22 01:42 UTC, Bojo992 requested changes
I think you would need to add Testcontainer for MySql

2024-11-26 19:30 UTC, plutowootoe commented
> Can you change which brunch you are pushing to dev, I will take a look at the tests later today, sorry just seen pr.

Added changes

2024-11-27 17:36 UTC, oakwoodwolf approved these changes

2024-12-02 13:59 UTC, Bojo992 requested changes
You would need to add something to mock kafka in bouth of test files.

2024-12-02 13:59 UTC, Bojo992 commented on project/src/test/java/com/cs4337/project/ChatControllerTests.java
> +        );
There is better way to make is with builder

2024-12-02 15:26 UTC, Bojo992 approved these changes
![it's-done-ray-johnson](https://github.com/user-attachments/assets/ee350dd0-fc43-4a18-a975-77b853433258)

2024-12-02 15:26 UTC, Bojo992 commented on project/src/test/java/com/cs4337/project/ChatControllerTests.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
You would need to add a variable that would represent random port

2024-12-03 01:26 UTC, merged